# Generated by Django 3.0.5 on 2021-02-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataDjango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=50)),
                ('created_at', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=200)),
                ('text_emotion', models.CharField(max_length=30)),
                ('locations', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
            ],
        ),
    ]
