# Generated by Django 3.0.5 on 2021-02-28 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadjango',
            name='id_str',
        ),
    ]
