# Generated by Django 3.0.5 on 2021-02-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_datadjango_id_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadjango',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='datadjango',
            name='text',
            field=models.TextField(),
        ),
    ]
