# Generated by Django 3.0.5 on 2021-02-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210228_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDjango2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('text', models.TextField()),
                ('text_emotion', models.CharField(max_length=30)),
                ('locations', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
            ],
        ),
    ]
